import type { Metadata } from "next";
import "./globals.css";
import { AuthGuard } from "@/components/auth-guard";
import { NavbarWrapper } from "@/components/navbar-wrapper";

export const metadata: Metadata = {
  title: "ArgusV ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="min-h-screen bg-background text-foreground">
          <AuthGuard />
          <NavbarWrapper />
          {children}
        </div>
      </body>
    </html>
  );
}
